server:
  port: 8082

token:
  expiration_time: 90000000
  secret: hjkahkchjsdhcksdcusuchde

spring:
  application:
    name: registration-service
  datasource:
    username: postgres
    password: Root1234
    url: jdbc:postgresql://project-management-system-database.c4vwssblkshy.ap-south-1.rds.amazonaws.com:5432/RegistrationDB
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8095/eureka

client:
  baseUrl: https://u0bqod1gs3.execute-api.ap-south-1.amazonaws.com/dev