server:
  port: 8082

token:
  expiration_time: 90000000
  secret: hjkahkchjsdhcksdcusuchde

spring:
  application:
    name: registration-service
  datasource:
    username: postgres
    password: Anumegha123
    url: jdbc:postgresql://database-1.cndivgctwt1v.us-west-2.rds.amazonaws.com:5432/RegistrationDB
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8095/eureka

client:
  baseUrl: https://u1vcnuupy5.execute-api.us-west-2.amazonaws.com/dev